name: Android CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up config files
        working-directory: '.'
        run: cp ./.github/ci/apiKeys.properties ./RemootioAndroidAuto/apiKeys.properties

      - name: Decode Keystore
        working-directory: ./RemootioAndroidAuto
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}

        run: echo -n "$ENCODED_STRING" | base64 -d  > "$SIGNING_KEY_STORE_PATH"

      - name: Grant execute permission for gradlew
        working-directory: ./RemootioAndroidAuto
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./RemootioAndroidAuto
        run: ./gradlew build

      - name: Generate Release APK file
        working-directory: ./RemootioAndroidAuto
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Generate Release bundle
        working-directory: ./RemootioAndroidAuto
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Archive APK and Android App Bundle files
        uses: actions/upload-artifact@v3
        with:
          name: package-and-bundle
          path: |
            ./RemootioAndroidAuto/automotive/build/outputs/apk/release/automotive-release.apk
            ./RemootioAndroidAuto/automotive/build/outputs/bundle/release/automotive-release.aab

      - name: Publish GitHub release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v0.1.15
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            ./RemootioAndroidAuto/automotive/build/outputs/apk/release/automotive-release.apk
            ./RemootioAndroidAuto/automotive/build/outputs/bundle/release/automotive-release.aab
