name: Android CI

on:
  push:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: bump version code
        run: ./scripts/bumpVersionCode.sh

      - name: bump version name
        run: ./scripts/bumpVersionName.sh

      - name: commit version changes
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'Version CI'
          git config --global user.email 'chamilton0@users.noreply.github.com'
          git commit -am "ci(version): updates version"
          git push --force

  build:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Set up config files
        run: cp ./.github/ci/apiKeys.properties ./RemootioAndroidAuto/apiKeys.properties

      - name: Decode Keystore
        working-directory: RemootioAndroidAuto
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}

        run: echo -n "$ENCODED_STRING" | base64 -d  > keystore.jks

      - name: Grant execute permission for gradlew
        working-directory: RemootioAndroidAuto
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: RemootioAndroidAuto
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew build

      - name: Generate Release APK file
        working-directory: RemootioAndroidAuto
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Generate Release bundle
        working-directory: RemootioAndroidAuto
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Archive APK and Android App Bundle files
        uses: actions/upload-artifact@v3
        with:
          name: package-and-bundle
          path: |
            ./RemootioAndroidAuto/automotive/build/outputs/apk/release/automotive-release.apk
            ./RemootioAndroidAuto/automotive/build/outputs/bundle/release/automotive-release.aab

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: android-package
          path: ./RemootioAndroidAuto/automotive/build/outputs/apk/release/automotive-release.apk
      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: android-app-bundle
          path: ./RemootioAndroidAuto/automotive/build/outputs/bundle/release/automotive-release.aab

  publish_release:
    runs-on: ubuntu-latest
    needs:
      build
    steps:
      - uses: actions/checkout@v3

      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: android-package

      - name: Download bundle
        uses: actions/download-artifact@v3
        with:
          name: android-app-bundle

      - name: Extract Version
        id: version
        working-directory: RemootioAndroidAuto/automotive
        run: |
          # Use grep and awk to extract the version from build.gradle
          version=$(grep -oP 'versionName\s+"\K[^"\047]+' build.gradle)
          echo "Extracted version: $version"
          echo "::set-output name=release_version::$version"

      - name: Publish GitHub release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v0.1.15
        with:
          prerelease: true
          files: |
            automotive-release.apk
            automotive-release.aab
          tag_name: ${{ steps.version.outputs.release_version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Google Play
        if: github.ref == 'refs/heads/master'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: chamilton0.remootioandroidws
          releaseFiles: automotive-release.aab
          track: internal
          status: draft
