name: Android CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: ./RemootioAndroidAuto
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: ./RemootioAndroidAuto
        run: ./gradlew build

      - name: Generate APK file
        working-directory: ./RemootioAndroidAuto
        run: ./gradlew assembleDebug

      - name: Archive APK file
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: ./RemootioAndroidAuto/automotive/build/outputs/apk/debug/automotive-debug.apk
